### ISSUE TITLE
Syntax different in Windows and Linux

### ISSUE THREAD

**Issue by javajeff18** [atom/one-light-syntax#45] opened 2018-03-30 14:07 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Windows has different syntax then Linux
2. [Second Step]
3. [and so on...]

**Expected behavior:** I expect the syntax to be the same in both OSes

**Actual behavior:** Windows shows the inside of a style as the same color as content.

**Reproduces how often:** It happens all the time

### Versions
Atom Version: 1.25.0
one-light-syntax 1.8.2
Windows Version:
![windows](https://user-images.githubusercontent.com/34710596/38140482-e30c8b92-3401-11e8-8935-64a94045c355.png)
Linux Version:
![linux](https://user-images.githubusercontent.com/34710596/38140484-e66f5a08-3401-11e8-84b0-4a2df8dea73d.png)

I have the same issue with the one dark syntax.
![windows-dark](https://user-images.githubusercontent.com/34710596/38140652-be32a422-3402-11e8-8c16-d4aa0e022807.png)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
The Windows version does not seem right.  It makes it very hard to use when content blends in with code.

**Comment by Arcanemagus** [comment] 2018-03-30 15:58
Could you double check that the Linux install is on Atom v1.25.0? `language-html` was updated to style `style` elements as CSS code (since they are) in Atom v1.25.0.

**Comment by Arcanemagus** [comment] 2018-03-30 17:53
Support for that was added in https://github.com/atom/language-html/pull/170, with the idea being that when you are coding you want code to show as code, not text 😉.

I'm marking this as closed since it's not a bug with `one-light-syntax` but feedback about `language-html`.

Thanks very much for the report!

**Closed by Arcanemagus** 2018-03-30 17:53 UTC
Labels: more-information-needed

**Comment by javajeff18** [comment] 2018-03-30 19:43
I really do not understand your comments.  My issue is that the code shows as text.  I would like them completely separate colors.  I consider a style as part of the code.  So the syntax color scheme does not work anymore in one-light or one-dark.

**Comment by Arcanemagus** [comment] 2018-03-30 19:51
Please file an issue on `language-html` then, that has nothing to do with the theme in use.

The change is due to https://github.com/atom/language-html/pull/170 making `language-html` highlight `style="foo"` as CSS instead of just text.
